/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as JogoGameIdRouteImport } from './routes/jogo.$gameId'
import { Route as MundoWorldIdRouteImport } from './routes/mundo.$worldId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoGameIdRoute = JogoGameIdRouteImport.update({
  id: '/jogo/$gameId',
  path: '/jogo/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const MundoWorldIdRoute = MundoWorldIdRouteImport.update({
  id: '/mundo/$worldId',
  path: '/mundo/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/jogo/$gameId': typeof JogoGameIdRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/jogo/$gameId': typeof JogoGameIdRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/jogo/$gameId': typeof JogoGameIdRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/album' | '/jogo/$gameId' | '/mundo/$worldId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/album' | '/jogo/$gameId' | '/mundo/$worldId'
  id: '__root__' | '/' | '/album' | '/jogo/$gameId' | '/mundo/$worldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  JogoGameIdRoute: typeof JogoGameIdRoute
  MundoWorldIdRoute: typeof MundoWorldIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo/$gameId': {
      id: '/jogo/$gameId'
      path: '/jogo/$gameId'
      fullPath: '/jogo/$gameId'
      preLoaderRoute: typeof JogoGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mundo/$worldId': {
      id: '/mundo/$worldId'
      path: '/mundo/$worldId'
      fullPath: '/mundo/$worldId'
      preLoaderRoute: typeof MundoWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  JogoGameIdRoute: JogoGameIdRoute,
  MundoWorldIdRoute: MundoWorldIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
